name: chitrwallpaperapp
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  http: ^0.12.1
  curved_navigation_bar: ^0.3.2
  like_button: ^0.2.0
  image_downloader: ^0.19.2
  overlay_support: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
     - family: DancingScript
       fonts:
         - asset: fonts/DancingScript-Regular.ttf

