name: chitrwallpaperapp
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.1
  salomon_bottom_bar: ^2.0.0
  like_button: ^0.2.0
  image_downloader: ^0.19.2
  overlay_support: ^1.0.4
  gradient_text: ^1.0.2
  cached_network_image: ^2.3.3
  material_floating_search_bar: ^0.2.3
  flappy_search_bar: 1.4.1
  flutter_staggered_grid_view: ^0.3.2
  flutter_blurhash: ^0.5.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
